=== TarmazakovEvgeny/db36/mephi.dtd
<!ELEMENT university (faculty)>
<!ELEMENT faculty (department)>
<!ELEMENT department (group1,group2)>
<!ELEMENT group1 (student+)>
<!ELEMENT group2 (student+)>
<!ELEMENT student (#PCDATA)>
<!ATTLIST university 
name CDATA #REQUIRED
address CDATA #IMPLIED>
<!ATTLIST faculty
name CDATA #REQUIRED
korp CDATA #IMPLIED
dekan CDATA #REQUIRED>
<!ATTLIST department
name CDATA #REQUIRED
number CDATA #REQUIRED
website CDATA #IMPLIED>
<!ATTLIST group1 number CDATA #REQUIRED>
<!ATTLIST group2 number CDATA #REQUIRED>

=== TarmazakovEvgeny/db36/mephi.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!DOCTYPE university SYSTEM "mephi.dtd">

<university   name="Mephi" address="Russia, Moscow city, Kashirskoe freeway 31">
    <faculty name="KiB" korp="K" dekan="Efseev">
        <department name="Information system and technology" number="36" website="www.kaf36.ru">
            <group1 number="k5-361">
                <student>Anisimova</student>
                <student>Artemev</student>
		<student>Bybenko</student>
		<student>Dzheloukhova</student>	
		<student>Mikheev</student>
		<student>Pivovarov</student>
		<student>Samsonov</student>
		<student>Sidorova</student>
		<student>Soloveva</student>
		<student>Tarmazakov</student>
		<student>Titorenko</student>
		<student>Shtanko</student>
            </group1>
            <group2 number="k5-362">
                <student>Erochin</student>
		<student>Strekalov</student>
                <student>Skok</student>
            </group2>
        </department>
    </faculty>
</university>
